### ISSUE TITLE
Nothing appear after installation 

### ISSUE THREAD

**Issue by isfzade** [MichaelAquilina/python-tools#99]
I have just installed this package. However nothing appear on Atom. Tried to press f5 nothing appears. Also how to select the starting code line to debug? 
I am an beginner please explain what to do more detailed.

**Comment by MichaelAquilina** [comment]
Hi @isfzade `python-tools` is no longer maintained very well because I have stopped using atom. I would suggest installing `python-autocomplete` which provides autocompletion and some of the functionality in this package. I am not aware of any package in atom that provices debugging within the atom editor though.
